---
#Add text below.
ticks: "20"
x1: ""
y1: ""
z1: ""
x2: ""
y2: ""
z2: ""
x3: ""
y3: ""
z3: ""
x4: ""
y4: ""
z4: ""
x5: ""
y5: ""
z5: ""
x6: ""
y6: ""
z6: ""
x7: ""
y7: ""
z7: ""
x8: ""
y8: ""
z8: ""
x9: ""
y9: ""
z9: ""
x10: ""
y10: ""
z10: ""
x11: ""
y11: ""
z11: ""
x12: ""
y12: ""
z12: ""
...
